version: '3.10'

services:
  web:
    build: .
    command: ["sh", "-c", "python3 app/app.py"]

    volumes:
      - .:/app
    
    ports:
      - "8000:8000"
    
    environment:
      DATABASE_URL: "sqlite:///./mi_almacen.db"
